#!/bin/bash
# Autor: Edmundo Cespedes A.
# Licencia: GNU GPLv2
# NOMBRE: # cpbkpsigma
# FUNCION:
# Verificacion y Copia en el servidor de archivos para Backup.
# ------------------------------------------------------------------
# Variables
#
# Glovales
CARPETA=0;
# Fecha
DIA=$(date +%d);
MES=$(date +%m);
ANO=$(date +%Y);
# En esta seccion se configura todos los parametros necesarios para el script.
# Directorio
DIR_ORIGEN="/backup/PROD/export/";
DIR_DESTINO="/mnt/Bkp01/sigmadb/";
# Archivos
ARCH_BKP='fullexpPROD.dmp.gz';
ARCH_LOG='fullexpPROD.log';
#
# Funciones
#
# Funcion Crear Directorio
# Los parametros en viados a  la funcion son $1=DIR_DESTINO $2=CARPETA  
func_create_dir(){
    echo "Creando Directorio /$2";
    local dirbkp=$1$2;
    mkdir $dirbkp;
    msg="Directorio /$2 creado";
    dirbkp_st=1
    echo $msg;
}
# Funcion Verificar Directorio 
# Los parametros en viados a  la funcion son $1=DIR_DESTINO $2=CARPETA  
func_verifi_dir(){
    local dirbkp=$1$2;
    echo Verificando la existencia del Directorio '/'$2;
    sleep 1
    if [ -d $dirbkp ];
    then
        echo Directorio '/'$2 encontrado;
        dirbkp_st=1
    else
        echo Directorio '/'$2 no encontrado;
        func_create_dir $1 $2;
    fi
}
# Funcion de Verificacion de Archivos
# Los parametros enviados a  la funcion son $1=DIR_DESTINO $2=ARCH_BKP 
# o ARCH_LOG 
func_verifi_arch(){
    # Origen
    local arch="$1$2";
    # Verificando Archivo
    echo "Verificando la existencia de archivos $2";
    if [ -f $oarch1 ];
    then
        echo "Archivo $2 encontrado";
    else
        echo "Archivo $2 no encontrado";
        echo "Generando Backup SIGMA";
        # Cambio de usuario para poder ejecutar la copia de seguridad
        su - oracle -c "/backup/PROD/export/fullexpPROD.sh";
    fi
}
# Funcion de Copiado de archvos
# Los parametros enviados a  la funcion son $1=DIR_ORIGEN $2=DIR_DESTINO 
# $3=ARCH_BKP o ARCH_LOG $4=CARPETA  
func_copy_arch(){
    sleep 1
    echo Copiando: $3; 
    echo de $1 a $2$4;
    cp -fv $1$3 $2$4;
    echo Copia Realizada de $3;
}
# Funcion de Montado y desmontado del particion NFS del servidor de Backup
# Los parametros para la funcion son 1=montado y 2=desmontado
func_mount(){
    case $1 in
        1)
            mount 192.168.14.100:/mnt/bckvm01/dump /mnt/Bkp01;
            echo "Directorio Montado";
        ;;
        2)
            umount 192.168.14.100:/mnt/bckvm01/dump /mnt/Bkp01;
            echo "Directorio Desmontado";
        ;;
        *)
            echo "introduzca un parametro al comando"; 
            echo "1) Montar Particion";
            echo "2) Desmontar Particion";
            echo "Ejemplo func_mount 1";
        ;;
    esac
}
# Funcion para verificar si la particion para realizar los backups esta montada
# El parametro para la funcion es $1=DIR_DESTINO
func_verifi_mount(){
    local dirmount=$1;
    if [ -d $dirmount ];
    then
        echo "Directorio Montado";
        sleep 1;
        #clear;
    else
        echo "Directorio no Montado";
        echo "Montando directorio";
        sleep 1;
        func_mount 1;
        #clear;
    fi
}
# -----------------------------------------------------------------------------
# SCRIPT
# -----------------------------------------------------------------------------
#
clear;
echo Iniciando Copia de Backup SIGMA;
#
# Verificando si esta montada la Particion de Red 
#
func_verifi_mount $DIR_DESTINO;
#
# Verificando y/o creando carpeta del mes
#
CARPETA=$ANO$MES;
func_verifi_dir $DIR_DESTINO $CARPETA;
#
# Verificando y/o creando directorio destino
#
CARPETA=$ANO$MES$DIA;
DIR_DESTINO=$DIR_DESTINO$ANO$MES'/';
func_verifi_dir $DIR_DESTINO $CARPETA;
#
# Copia de los archivos de backup a la particion de red
#
if [ $dirbkp_st == 1 ];
then
    func_copy_arch $DIR_ORIGEN $DIR_DESTINO $ARCH_BKP $CARPETA;
    func_copy_arch $DIR_ORIGEN $DIR_DESTINO $ARCH_LOG $CARPETA;
    func_mount 2;
    msg="Copias de Backup realizado con exito en /$CARPETA";
else
    msg="No se pudo realizar el Backup no se tiene acceso a las carpetas";
fi
# Mostramos el mensaje de finalizacion del script
echo $msg;
