#!/bin/bash
# Autor: Edmundo Cespedes A.
# Licencia: GNU GPLv2
# NOMBRE: # rmbkpsigma
# FUNCION:
# Verificacion y Copia en el servidor de archivos para Backup.
# ------------------------------------------------------------------------------ 
# VARIABLES
# ------------------------------------------------------------------------------
#
DIR_BKP="/u05/flash_recovery_area/PROD/PROD/backupset/";
CARPETA=0;
# Fecha
DIA=$(date +%d);
MES=$(date +%m);
ANO=$(date +%Y);
# ------------------------------------------------------------------------------
# FUNCIONES
# ------------------------------------------------------------------------------
# Funcion para probar el script creando Directorios
function_test(){
# Numero de carpetas a ser creadas para la prueba
    local nrodir=8;
    local day=$DIA;
    for((i=0;i<=$nrodir;i++))
    do
        #echo $day;
        local dirmake=$DIR_BKP$ANO'_'$MES'_'$day;
        #echo $dirmake;
        mkdir $dirmake;
        ((day=$day-1));
    done
}
# Funcion de mesaje temporal
function_msg(){
    echo -n $1;
    sleep 1;
    tput el1;
    tput cub 666;
}
# Funcion Verificar Directorio 
# Los parametros en viados a  la funcion son $1=DIR_BKP $2=CARPETA 
func_verifi_dir(){
    local dirbkp=$1$2;
    function_msg "Verificando la existencia del Directorio /$2";
    if [ -d $dirbkp ];
    then
        function_msg "Directorio /$2 encontrado";
        dirbkp_st=1;
    else
        function_msg "Directorio /$2 no encontrado";
        dirbkp_st=0;
    fi
}
# Funcion pra contar los directorios
function_contar_dir(){
    NDIR=$(find $1 -iname "$ANO*" -type d | wc -l);
}
# Funcion para elimminar el directorio
function_remove_dir(){
    case $3 in
        1)
            function_msg "Eliminando el Directorio /$2";
            rm -rf $1$2;
            function_msg "Directorio /$2 ELIMINADO";
        ;;
        0)
            function_msg "No hay Directorio para eliminar";
        ;;
        *)
            function_msg "Introduzca un parametro al comando";
        ;;
    esac
}
# ------------------------------------------------------------------------------
# SCRIPT
# ------------------------------------------------------------------------------
# Comprobado la existencia del directorio que contine los Backup
if [ -d $DIR_BKP ];
then
    echo "Diirectorio $DIR_BKP ENCONTRADO";
# Descomentar para crera las carpetas para las pruebas
    #function_test;
    echo "Directorios Presentes:";
    ls $DIR_BKP;
# Contando los directorios dentro del directorio raiz que los contien     
    function_contar_dir $DIR_BKP;
    echo "Se Eliminaran ** $((NDIR-1)) ** Directorios";
# Realizando comprobaicones de los directorios    
    for (( i=1; i<$NDIR; i++ ))
    do
        function_msg "Instancia Nro.$i";
# Verificando la exixtencia del directorio a eliminar
        ((DIA=$DIA-1));
        CARPETA=$ANO"_"$MES"_"$DIA;
        func_verifi_dir $DIR_BKP $CARPETA;
        sleep 1;
# Eliminado el directorio encontrado
        function_remove_dir $DIR_BKP $CARPETA $dirbkp_st;
    done
else
    echo "Directorio NO encontrado";
fi
echo "Eliminacion realizada";
echo "Directorios Presentes:";
ls $DIR_BKP;
